/* Autogenerated with DRAKON Editor 1.31 */
#include "PRC.h"


static void LOADATT();







static void LOADATT() {
}

 KanalRR::KanalRR(
    duoble F,
    int Mod_kanalNum,
    int Blok_kanalNum
) {
}

 KanalRR::~KanalRR() {
}

void KanalRR::ATT2SET(
    int DB
) {
    // item 251
    if (DB>61) {
        // item 254
        ATT2 = 61;
    } else {
        // item 249
        ATT2 = DB;
    }
    
    // item 256
    if (DB<0) {
        // item 259
        ATT2 = 0;
    } else {
    }
    
}

void KanalRR::ATT3SET(
    int DB
) {
    // item 269
    if (DB>61) {
        // item 272
        ATT3 = 61;
    } else {
        // item 267
        ATT3 = DB;
    }
    
    // item 274
    if (DB<0) {
        // item 277
        ATT3 = 0;
    } else {
    }
    
}

void KanalRR::ATTSET(
    int DB
) {
    // item 234
    if (DB>61) {
        // item 237
        ATT1 = 61;
    } else {
        // item 232
        ATT1 = DB;
    }
    
    // item 240
    if (DB<0) {
        // item 243
        ATT1 = 0;
    } else {
    }
    
}

void KanalRR::PRESELSET(
    int PRES
) {
    // item 288
    Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
    
    // item 283
    if (Pres<7) {
        // item 286
        LNAD =0;
    } else {
        // item 287
        LNAD = 1;
    }
    
}

int KanalRR::REGLoad(
    int R
) {
    // item 1420001
    if (R == 0) {
        // item 153
        return  AdrMod|NKanal[Kanal].Pres_Band_LNA|PRES;
    } else {
    }
    
    // item 1420002
    if (R == 1) {
        // item 166
        return  AdrMod|NKanal[Kanal].Pres_Fil|LNA;
    } else {
    }
    
    // item 1420003
    if (R == 2) {
        // item 168
        return  AdrMod|NKanal[Kanal].Pch1_Sw|PCH3035;
    } else {
    }
    
    // item 1420004
    if (R == 3) {
    } else {
        // item 1420005
        UnexpectedBranch(R);
    }
    
    // item 169
    return  AdrMod|NKanal[Kanal].Pch2_Sw|CTRLIN;
    
}

void KanalRR::SETPCH1(
    int P3000
) {
    // item 164
    PCH3035 = P3000;
    
}

void KanalRR::SETPCH2(
    int GET,,
    int IN
) {
    // item 182
    CTRLN = INPCH2<1|UPGET
    
}

void KanalRR::SETPRES(
    int VALPRES
) {
    // item 221
    PRES = VALPRES<<12;
    
}

void KanalRR::SetFin(
    double F,
    int K
) {
    // item 171
    Kanal = K;
    
    // item 16
    if (F>=30) {
    } else {
        goto exit_door;
    }
    
    // item 35
    if (F>=50) {
    } else {
        // item 290
        PRES = 0;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 0;
        PCH3035 = 1;
        CTRLIN = 1;
        goto exit_door;
    }
    
    // item 27
    if (F>=70) {
    } else {
        // item 291
        PRES = 1;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 0;
        PCH3035 = 1;
        CTRLIN = 1;
        goto exit_door;
    }
    
    // item 50
    if (F>=105) {
    } else {
        // item 292
        PRES = 2;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 0;
        PCH3035 = 1;
        CTRLIN = 1;
        goto exit_door;
    }
    
    // item 43
    if (F>=175) {
    } else {
        // item 293
        PRES = 3;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 0;
        PCH3035 = 1;
        CTRLIN = 1;
        goto exit_door;
    }
    
    // item 63
    if (F>=315) {
    } else {
        // item 294
        PRES = 4;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 0;
        PCH3035 = 1;
        CTRLIN = 1;
        goto exit_door;
    }
    
    // item 57
    if (F>=525) {
    } else {
        // item 295
        PRES = 5;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 0;
        PCH3035 = 1;
        CTRLIN = 1;
        goto exit_door;
    }
    
    // item 77
    if (F>=805) {
    } else {
        // item 296
        PRES = 6;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 0;
        PCH3035 = 1;
        CTRLIN = 1;
        goto exit_door;
    }
    
    // item 71
    if (F>=1250) {
    } else {
        // item 297
        PRES = 7;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 1;
        PCH3035 = 1;
        CTRLIN = 1;
        goto exit_door;
    }
    
    // item 92
    if (F>=1650) {
    } else {
        // item 298
        PRES = 8;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 1;
        PCH3035 = 1;
        CTRLIN = 1;
        goto exit_door;
    }
    
    // item 86
    if (F>=2550) {
    } else {
        // item 299
        PRES = 9;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 1;
        PCH3035 = 1;
        CTRLIN = 1;
        goto exit_door;
    }
    
    // item 104
    if (F>=1650) {
    } else {
        // item 300
        PRES = 10;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 1;
        PCH3035 = 1;
        CTRLIN = 1;
        goto exit_door;
    }
    
    // item 98
    if (F>=2550) {
        // item 302
        PRES = 12;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 1;
        PCH3035 = 1;
        CTRLIN = 1;
    } else {
        // item 301
        PRES = 11;
        Pres_UPR_Kluch = DIAPAZON[KanalNum_B_Mod][PRES];
        LNAD = 1;
        PCH3035 = 1;
        CTRLIN = 1;
    }
    
    exit_door:;
}

void KanalRR::SetFrOFFSET(
    int Edit2
) {
    // item 342
    BLOKRR->MFC1->Sint1_LMX2594->SetFreq(Edit2->Text.ToDouble());
    Form2->AdvSpinEdit4->Value = BLOKRR->MFC1->Sint1_LMX2594->VCO_CAPCTRL_ST;
    Form2->AdvSpinEdit3->Value = BLOKRR->MFC1->Sint1_LMX2594->VCO_DACISET_ST;
    BLOKRR->LoadLMX1();
    // item 341
    i = Form4->binary_search(Edit2->Text.ToDouble(),0,268)-1;
    RichEdit1->Clear();
    RichEdit1->Lines->Add(i);
    RichEdit1->Lines->Add("Fl=" + FloatToStr(Form4->Polosa[i].DFv));
    RichEdit1->Lines->Add("Fp=" + FloatToStr(Form4->Polosa[i+1].DFv));
    RichEdit1->Lines->Add("M=" + IntToStr(Form4->Polosa[i].DM));
    RichEdit1->Lines->Add("K=" + IntToStr(Form4->Polosa[i].K));
    RichEdit1->Lines->Add("OUT=" + IntToStr(Form4->Polosa[i].MOUT));
    RichEdit1->Lines->Add("N=" + IntToStr(Form4->Polosa[i].DN));
    RichEdit1->Lines->Add("OUT2=" + IntToStr(Form4->Polosa[i].MOUT2));
    RichEdit1->Lines->Add("CAP1=" + IntToStr(Form4->Polosa[i].CAP1));
    Edit1->Text = 10;
    // item 343
    Edit4->Text	= Edit2->Text.ToDouble()/(Form4->Polosa[i].DM*Form4->Polosa[i].MOUT)  - Form4->Polosa[i].K*Edit2->Text.ToDouble()/Form4->Polosa[i].DN -1000;
    BLOKRR->MFC1->Sint1_LMX2594->NSET(Form4->Polosa[i].DN);
    BLOKRR->LoadLMXUNO(34);
    BLOKRR->LoadLMXUNO(36);
    BLOKRR->MFC1->Sint1_LMX2594->FRSET(0);
    BLOKRR->LoadLMXUNO(42);
    BLOKRR->LoadLMXUNO(43);
    BLOKRR->LoadLMXUNO(BLOKRR->MFC1->Sint1_LMX2594->VCO_CAPCTRL_FORCE(1));
    BLOKRR->LoadLMXUNO(BLOKRR->MFC1->Sint1_LMX2594->VCO_CAPCTRL(Form2->AdvSpinEdit4->Value - AdvSpinEdit1->Value));
    
    // item 3290001
    if (NOUT == 1) {
        // item 338
        // item 312
        Form2->ComboBox11->ItemIndex=1;
        Form2->ComboBox12->ItemIndex=1;
        BLOKRR->MFC1->Sint1_LMX2594->OUTAMUX(1);
        BLOKRR->MFC1->Sint1_LMX2594->OUTBMUX(1);
        // item 326
        Form1->BLOKRR->LoadLMXUNO(Form1->BLOKRR->MFC1->Sint1_LMX2594->OUTAMUX(1)); //R45
        // item 327
        Form1->BLOKRR->LoadLMXUNO(Form1->BLOKRR->MFC1->Sint1_LMX2594->OUTBMUX(1)); //R46
        goto exit_door;
    } else {
    }
    
    // item 3290002
    if (NOUT == 2) {
        // item 321
        Form2->ComboBox10->ItemIndex=0;
        Form2->ComboBox11->ItemIndex=0;
        Form2->ComboBox12->ItemIndex=0;
        // item 323
        Form1->BLOKRR->LoadLMXUNO(Form1->BLOKRR->MFC1->Sint1_LMX2594->CHANDiV(0)); //R75[10:6]
        // item 324
        Form1->BLOKRR->LoadLMXUNO(Form1->BLOKRR->MFC1->Sint1_LMX2594->OUTAMUX(0)); //R45
        // item 325
        Form1->BLOKRR->LoadLMXUNO(Form1->BLOKRR->MFC1->Sint1_LMX2594->OUTBMUX(0)); //R46
    } else {
    }
    
    exit_door:;
}



